name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: 'starter/frontend/.nvmrc'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/node_modules
          key: frontend-node-${{ runner.os }}-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            frontend-node-${{ runner.os }}-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: 'starter/frontend/.nvmrc'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/node_modules
          key: frontend-node-${{ runner.os }}-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            frontend-node-${{ runner.os }}-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: starter/frontend
        run: CI=true npm test

  build:
    name: Build
    needs:
      - lint
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: 'starter/frontend/.nvmrc'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/node_modules
          key: frontend-node-${{ runner.os }}-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            frontend-node-${{ runner.os }}-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: starter/frontend
        run: CI=true npm test

      - name: Build Docker image
        working-directory: starter/frontend
        env:
          REACT_APP_MOVIE_API_URL: http://localhost:5000
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL \
            --tag mp-frontend:latest .
